apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netverify-argocd
  namespace: argocd
spec:
  source:
    path: netverify
    repoURL: https://github.com/ErickaRamosFacephi/argo-test.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app
  project: default
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
