apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netverify
  namespace: argocd
spec:
  source:
    path: netverify
    repoURL: https://github.com/ErickaRamosFacephi/argo-test.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  project: default

